export type Loja = {
  id: string;
  user_id: string;
  nome: string;
  slug: string;
  descricao: string | null;
  whatsapp: string | null;
  instagram: string | null;
  logo_url: string | null;
  capa_url: string | null;
  cor_principal: string;
  cor_secundaria: string;
  ativa: boolean;
  created_at: string;
  sobre_loja?: string | null;
  estilo_loja?: string | null;
  diferencial_1?: string | null;
  diferencial_2?: string | null;
  diferencial_3?: string | null;
  dona_nome?: string | null;
  dona_foto_url?: string | null;
  dona_historia?: string | null;
  dona_instagram?: string | null;
  endereco?: string | null;
  cidade?: string | null;
  estado?: string | null;
  horario_atendimento?: string | null;
  link_maps?: string | null;
  tipo_atendimento?: string | null;
};
