import type { Categoria } from "./categoria";

export type Produto = {
  id: string;
  loja_id: string;
  categoria_id: string | null;
  nome: string;
  slug: string;
  descricao: string | null;
  detalhes: string | null;
  preco: number;
  preco_promocional: number | null;
  imagem_url: string | null;
  galeria_urls: string[] | null;
  ativo: boolean;
  destaque: boolean;
  estoque: number | null;
  sku: string | null;
  ordem: number;
  created_at: string;
  updated_at: string;
  tipo_produto?: "produto" | "kit" | string | null;
  badge?: string | null;
  observacao?: string | null;
  colecao?: string | null;
  material?: string | null;
  banho_cor?: string | null;
  medidas?: string | null;
  peso?: string | null;
  tamanho?: string | null;
  fechamento?: string | null;
  cuidados?: string | null;
  preco_custo?: number | null;
  promocao_inicio?: string | null;
  promocao_fim?: string | null;
  estoque_minimo?: number | null;
  codigo_interno?: string | null;
  whatsapp_mensagem?: string | null;
  seo_titulo?: string | null;
  seo_descricao?: string | null;
  tags?: string[] | null;
  ocasiao?: string | null;
  categorias?: Pick<Categoria, "id" | "nome" | "slug"> | null;
};
