import type { Categoria } from "@/types/categoria";
import type { Produto } from "@/types/produto";

export const mockCategorias: Categoria[] = [
  { id: "mock-brincos", loja_id: "mock", nome: "Brincos", slug: "brincos", descricao: null, ativa: true, ordem: 1, created_at: "" },
  { id: "mock-pulseiras", loja_id: "mock", nome: "Pulseiras", slug: "pulseiras", descricao: null, ativa: true, ordem: 2, created_at: "" },
  { id: "mock-colares", loja_id: "mock", nome: "Colares", slug: "colares", descricao: null, ativa: true, ordem: 3, created_at: "" },
  { id: "mock-aneis", loja_id: "mock", nome: "Aneis", slug: "aneis", descricao: null, ativa: true, ordem: 4, created_at: "" },
  { id: "mock-kits", loja_id: "mock", nome: "Kits", slug: "kits", descricao: null, ativa: true, ordem: 5, created_at: "" }
];

const image = "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1200&auto=format&fit=crop";

export const mockProdutos: Produto[] = [
  {
    id: "mock-1",
    loja_id: "mock",
    categoria_id: "mock-brincos",
    nome: "Brinco Dourado Delicado",
    slug: "brinco-dourado-delicado",
    descricao: "Uma peça leve com brilho suave para o dia a dia.",
    detalhes: null,
    preco: 49.9,
    preco_promocional: null,
    imagem_url: image,
    galeria_urls: null,
    ativo: true,
    destaque: true,
    estoque: null,
    sku: null,
    ordem: 1,
    created_at: "",
    updated_at: "",
    tipo_produto: "produto",
    badge: "Novo",
    observacao: null,
    categorias: { id: "mock-brincos", nome: "Brincos", slug: "brincos" }
  },
  {
    id: "mock-2",
    loja_id: "mock",
    categoria_id: "mock-pulseiras",
    nome: "Pulseira Perola Premium",
    slug: "pulseira-perola-premium",
    descricao: "Perolas delicadas com acabamento sofisticado.",
    detalhes: null,
    preco: 79.9,
    preco_promocional: 69.9,
    imagem_url: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=1200&auto=format&fit=crop",
    galeria_urls: null,
    ativo: true,
    destaque: true,
    estoque: null,
    sku: null,
    ordem: 2,
    created_at: "",
    updated_at: "",
    tipo_produto: "produto",
    badge: "Promoção",
    observacao: null,
    categorias: { id: "mock-pulseiras", nome: "Pulseiras", slug: "pulseiras" }
  },
  {
    id: "mock-3",
    loja_id: "mock",
    categoria_id: "mock-colares",
    nome: "Colar Coracao Minimalista",
    slug: "colar-coracao-minimalista",
    descricao: "Minimalista, romantico e facil de combinar.",
    detalhes: null,
    preco: 89.9,
    preco_promocional: null,
    imagem_url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1200&auto=format&fit=crop",
    galeria_urls: null,
    ativo: true,
    destaque: false,
    estoque: null,
    sku: null,
    ordem: 3,
    created_at: "",
    updated_at: "",
    tipo_produto: "produto",
    badge: null,
    observacao: null,
    categorias: { id: "mock-colares", nome: "Colares", slug: "colares" }
  },
  {
    id: "mock-4",
    loja_id: "mock",
    categoria_id: "mock-aneis",
    nome: "Anel Ajustavel Dourado",
    slug: "anel-ajustavel-dourado",
    descricao: "Acabamento dourado com ajuste confortavel.",
    detalhes: null,
    preco: 59.9,
    preco_promocional: null,
    imagem_url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1200&auto=format&fit=crop",
    galeria_urls: null,
    ativo: true,
    destaque: false,
    estoque: null,
    sku: null,
    ordem: 4,
    created_at: "",
    updated_at: "",
    tipo_produto: "produto",
    badge: null,
    observacao: null,
    categorias: { id: "mock-aneis", nome: "Aneis", slug: "aneis" }
  },
  {
    id: "mock-kit-1",
    loja_id: "mock",
    categoria_id: "mock-kits",
    nome: "Kit Presente Rose",
    slug: "kit-presente-rose",
    descricao: "Uma combinacao delicada para presentear com carinho.",
    detalhes: null,
    preco: 149.9,
    preco_promocional: 129.9,
    imagem_url: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?q=80&w=1200&auto=format&fit=crop",
    galeria_urls: null,
    ativo: true,
    destaque: true,
    estoque: null,
    sku: null,
    ordem: 5,
    created_at: "",
    updated_at: "",
    tipo_produto: "kit",
    badge: "Kit",
    observacao: null,
    categorias: { id: "mock-kits", nome: "Kits", slug: "kits" }
  },
  {
    id: "mock-kit-2",
    loja_id: "mock",
    categoria_id: "mock-kits",
    nome: "Kit Dourado Elegante",
    slug: "kit-dourado-elegante",
    descricao: "Brilho suave em uma curadoria pronta para usar.",
    detalhes: null,
    preco: 179.9,
    preco_promocional: null,
    imagem_url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1200&auto=format&fit=crop",
    galeria_urls: null,
    ativo: true,
    destaque: false,
    estoque: null,
    sku: null,
    ordem: 6,
    created_at: "",
    updated_at: "",
    tipo_produto: "kit",
    badge: "Kit",
    observacao: null,
    categorias: { id: "mock-kits", nome: "Kits", slug: "kits" }
  }
];
